# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e63d33f71445c04ba490b93ecb3c1a2c7f5ccd00a8fa6b9954ebae41bffce83afe834dd40836785aed6a5aba5ea680fdb1f6f37440a1ea909d519bb25922db25

test:
  secret_key_base: bf234ed4ffc384c75519f8d33c621d634cdda04a491e7cbc0f0ab03616b2d65a9e71762efcb8ed795678097d20e1136537bd9c2d16dacc4e1c2db9b4e1cad0cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
